# Actividad: Carga y transformación de datos con Hugging Face

## Objetivo

Cargar un conjunto de datos desde Hugging Face utilizando Python y Pandas, realizar una transformación de los datos y generar un reporte descriptivo del DataFrame resultante.

## Dataset

- **Nombre:** Fast Food Restaurants
- **Repositorio:** `JasonZhouTI/Fast_Food_Restaurants`
- **Origen:** Hugging Face

## Transformación propuesta

Conservar únicamente los restaurantes que tengan una página web registrada, para trabajar con información disponible y generar un reporte de los datos transformados.

In [1]:

#preparar importaciones

import sys
from pathlib import Path

# Encontrar la raíz del proyecto
ROOT = Path.cwd().resolve()

while ROOT != ROOT.parent and not (ROOT / "src" / "clases_po").exists():
    ROOT = ROOT.parent

# Permitir importar las clases del proyecto
sys.path.insert(0, str(ROOT / "src"))

from clases_po import HFDatasetLoader, Reportes

import pandas as pd

print("Raíz del proyecto:", ROOT)
print("Importaciones realizadas correctamente")

Raíz del proyecto: /workspaces/analitica
Importaciones realizadas correctamente

/workspaces/analitica/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#Cargar el dataset desde Hugging Face


loader = HFDatasetLoader(
    dataset_name="JasonZhouTI/Fast_Food_Restaurants",
    split="train",
)

df_original = loader.load()

print("Dataset cargado correctamente")
print("Dimensiones:", df_original.shape)
print("Columnas:", df_original.columns.tolist())

df_original.head()

Repo card metadata block was not found. Setting CardData to empty.

Dataset cargado correctamente
Dimensiones: (10000, 10)
Columnas: ['address', 'city', 'country', 'keys', 'latitude', 'longitude', 'name', 'postalCode', 'province', 'websites']

,address,city,country,keys,latitude,longitude,name,postalCode,province,websites
0,324 Main St,Massena,US,us/ny/massena/324mainst/-1161002137,44.92130,-74.89021,McDonald's,13662,NY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
1,530 Clinton Ave,Washington Court House,US,us/oh/washingtoncourthouse/530clintonave/-7914...,39.53255,-83.44526,Wendy's,43160,OH,http://www.wendys.com
2,408 Market Square Dr,Maysville,US,us/ky/maysville/408marketsquaredr/1051460804,38.62736,-83.79141,Frisch's Big Boy,41056,KY,"http://www.frischs.com,https://www.frischs.com..."
3,6098 State Highway 37,Massena,US,us/ny/massena/6098statehighway37/-1161002137,44.95008,-74.84553,McDonald's,13662,NY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
4,139 Columbus Rd,Athens,US,us/oh/athens/139columbusrd/990890980,39.35155,-82.09728,OMG! Rotisserie,45701,OH,"http://www.omgrotisserie.com,http://omgrotisse..."

In [3]:
#Revisar los valores nulos 

print("Dimensiones del dataset original:", df_original.shape)

print("\nValores nulos por columna:")
print(df_original.isna().sum())

print("\nTotal de filas duplicadas:", df_original.duplicated().sum())

Dimensiones del dataset original: (10000, 10)

Valores nulos por columna:
address         0
city            0
country         0
keys            0
latitude        0
longitude       0
name            0
postalCode      0
province        0
websites      465
dtype: int64

Total de filas duplicadas: 0

In [4]:
#Transformar el dataframe 


df_transformado = df_original[
    df_original["websites"].notna()
    & df_original["websites"].astype("string").str.strip().ne("")
].copy()

print("Filas originales:", len(df_original))
print("Filas después de la transformación:", len(df_transformado))
print("Restaurantes excluidos:", len(df_original) - len(df_transformado))

df_transformado.head()

Filas originales: 10000
Filas después de la transformación: 9535
Restaurantes excluidos: 465

,address,city,country,keys,latitude,longitude,name,postalCode,province,websites
0,324 Main St,Massena,US,us/ny/massena/324mainst/-1161002137,44.92130,-74.89021,McDonald's,13662,NY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
1,530 Clinton Ave,Washington Court House,US,us/oh/washingtoncourthouse/530clintonave/-7914...,39.53255,-83.44526,Wendy's,43160,OH,http://www.wendys.com
2,408 Market Square Dr,Maysville,US,us/ky/maysville/408marketsquaredr/1051460804,38.62736,-83.79141,Frisch's Big Boy,41056,KY,"http://www.frischs.com,https://www.frischs.com..."
3,6098 State Highway 37,Massena,US,us/ny/massena/6098statehighway37/-1161002137,44.95008,-74.84553,McDonald's,13662,NY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
4,139 Columbus Rd,Athens,US,us/oh/athens/139columbusrd/990890980,39.35155,-82.09728,OMG! Rotisserie,45701,OH,"http://www.omgrotisserie.com,http://omgrotisse..."

In [5]:
#Importar la clase Reportes


import sys
from pathlib import Path

ROOT = Path.cwd().resolve()

while ROOT != ROOT.parent and not (ROOT / "src" / "clases_po").exists():
    ROOT = ROOT.parent

sys.path.insert(0, str(ROOT / "src"))

from clases_po import Reportes

print("Clase Reportes importada correctamente")

Clase Reportes importada correctamente

In [6]:
#Generar el reporte del DataFrame transformado


reportes = Reportes()

texto_reporte = reportes.generar_reporte(df_transformado)

print(texto_reporte)

REPORTE DEL DATAFRAME
============================================================
Filas: 9535
Columnas: 10
Duplicados: 0

Columnas y tipos:
- address: object
- city: object
- country: object
- keys: object
- latitude: float64
- longitude: float64
- name: object
- postalCode: object
- province: object
- websites: object

Valores nulos por columna:
- address: 0
- city: 0
- country: 0
- keys: 0
- latitude: 0
- longitude: 0
- name: 0
- postalCode: 0
- province: 0
- websites: 0

Estadísticas numéricas:
       latitude  longitude
count  9535.000   9535.000
mean     37.590    -91.141
std       4.991     17.794
min      19.345   -159.335
25%      34.036    -97.368
50%      38.339    -87.655
75%      41.141    -81.485
max      64.840    123.012

In [7]:
#Guardar el reporte en un archivo independiente


ruta_reporte = ROOT / "src" / "sincronicas" / "reportes" / "fast_food_restaurants_transformado.txt"

reportes.guardar_reporte(df_transformado, ruta_reporte)

print("Reporte guardado en:", ruta_reporte)

Reporte guardado en: /workspaces/analitica/src/sincronicas/reportes/fast_food_restaurants_transformado.txt

In [8]:
#Verificar que el archivo existe


print("¿Existe el archivo?", ruta_reporte.exists())

print("\nPrimeras líneas del reporte:\n")
print("\n".join(ruta_reporte.read_text(encoding="utf-8").splitlines()[:12]))

¿Existe el archivo? True

Primeras líneas del reporte:

REPORTE DEL DATAFRAME
============================================================
Filas: 9535
Columnas: 10
Duplicados: 0

Columnas y tipos:
- address: object
- city: object
- country: object
- keys: object
- latitude: float64

In [9]:
#Comprobar los resultados finales


print("RESUMEN FINAL DE LA ACTIVIDAD")
print("=" * 40)
print("Filas originales:", len(df_original))
print("Filas transformadas:", len(df_transformado))
print("Columnas:", len(df_transformado.columns))
print("Valores nulos en websites:", df_transformado["websites"].isna().sum())
print("Filas duplicadas:", df_transformado.duplicated().sum())
print("Reporte guardado:", ruta_reporte.exists())

RESUMEN FINAL DE LA ACTIVIDAD
========================================
Filas originales: 10000
Filas transformadas: 9535
Columnas: 10
Valores nulos en websites: 0
Filas duplicadas: 0
Reporte guardado: True